# Generated by Django 3.1.1 on 2020-09-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exposure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('level', models.CharField(blank=True, default='', max_length=100)),
                ('news_link', models.URLField(blank=True)),
                ('exposed_total', models.IntegerField(blank=True, default=0)),
                ('quarantined_children', models.IntegerField(blank=True)),
                ('quarantined_children_string', models.CharField(blank=True, default='', max_length=200)),
                ('quarantined_adults', models.IntegerField(blank=True)),
                ('quarantined_adults_string', models.CharField(blank=True, default='', max_length=200)),
                ('quarantined_total', models.IntegerField(blank=True)),
                ('quarantined_total_string', models.CharField(blank=True, default='', max_length=200)),
                ('remote_status', models.CharField(blank=True, default='', max_length=100)),
                ('publish_date', models.DateField(blank=True, null=True)),
                ('exposure_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
