# Generated by Django 3.1.1 on 2020-09-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='exposure_date',
            field=models.DateField(blank=True, help_text='When exposure occurred (if known)', null=True),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='publish_date',
            field=models.DateField(blank=True, help_text='When news of exposure was published', null=True),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='quarantined_adults',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='quarantined_children',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='quarantined_total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
