# Generated by Django 3.1.1 on 2020-09-01 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_auto_20200901_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='exposure',
            name='category',
            field=models.CharField(choices=[('school', 'School'), ('daycare', 'Daycare'), ('other', 'Other')], default='school', max_length=100),
        ),
    ]
