# Generated by Django 3.1.1 on 2020-09-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_auto_20200901_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='category',
            field=models.CharField(choices=[('school', 'School'), ('daycare', 'Daycare'), ('restaurant', 'Restaurant'), ('other', 'Other')], default='school', max_length=100),
        ),
    ]
