# Generated by Django 3.1.1 on 2020-09-04 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0005_auto_20200901_2022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exposure',
            options={'ordering': ['-publish_date']},
        ),
        migrations.AddField(
            model_name='exposure',
            name='exposed_string',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='exposure',
            name='infected_string',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='exposure',
            name='infected_total',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='exposure',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='category',
            field=models.CharField(choices=[('daycare', 'Daycare'), ('restaurant', 'Restaurant'), ('school', 'School'), ('other', 'Other')], default='school', max_length=100),
        ),
    ]
