# Generated by Django 3.1.1 on 2020-09-10 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0008_auto_20200910_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exposure',
            old_name='exposure_endTime',
            new_name='exposure_ended',
        ),
        migrations.RenameField(
            model_name='exposure',
            old_name='exposure_startTime',
            new_name='exposure_started',
        ),
    ]
