# Generated by Django 3.1.1 on 2020-09-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0009_auto_20200910_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exposure',
            name='category',
            field=models.CharField(choices=[('daycare', 'Daycare'), ('restaurant', 'Restaurant'), ('nightclub', 'Nightclub'), ('school', 'School'), ('transport', 'Transport'), ('other', 'Other')], default='school', max_length=100),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='exposure_ended',
            field=models.DateTimeField(blank=True, help_text='End of exposure', null=True),
        ),
        migrations.AlterField(
            model_name='exposure',
            name='exposure_started',
            field=models.DateTimeField(blank=True, help_text='Start of exposure', null=True),
        ),
    ]
